# Spring Boot Actuator
management:
  health:
    diskspace:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info
      basePath: /
      path-mapping:
        info: /version

## Generic application config
application:
  logging:
    audit:
      dir: c:/var/log/altinn-gateway
      file: audit.log
      dataSeparator: "|"

test:
  blacklist:
    404: tom-liste
    503: ikke-tilgjengelig
  rights:
    serviceCodes: 1234, 2456
    pidServiceCodes: "06045000883"
  mock:
    enabled: false

spring:
  security:
    user:
      name: user
      password: password
  cache:
    cache-names: delegations
    caffeine:
      spec: maximumSize=500, expireAfterWrite=50s
## Altinn integration
altinn:
  #  delegationsEndpoint: http://localhost:9991/altinn-mock/delegations
#  connectTimeout: <%= @connect_timeout %>
#  readTimeout: <%= @read_timeout %>
  keystore:
    type: JKS
    path: classpath:difi-testsertifikat.jks
    password: oBr8YZuZsbic4gpP
    keyAlias: avsender
    keyPassword: oBr8YZuZsbic4gpP
  serviceEndpoint: https://at23.altinn.cloud/maskinporten-api
  authorizationEndpoint: https://tt02.altinn.no/api/serviceowner/authorization
  apiKey: 86926452-CE1B-4960-9BA6-7E28D8DE3A53

maskinporten:
  iss: altinn_gateway
  aud: https://test1.maskinporten.no/
  resource: https://tt02.altinn.no/maskinporten-api/
  tokenEndpoint: http://test1.maskinporten.no/token
  scope: altinn:maskinporten/delegations.admin
  kid:



