# Spring Boot Actuator
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "version, info, health"
  health:
    defaults:
      enabled: true
    jms:
      enabled: true
    ldap:
      enabled: true
  endpoint:
    health:
      show-details: always

## Generic application config
application:
  logging:
    audit:
      dir: c:/var/log/altinn-gateway
      file: audit.log

test:
  blacklist:
    404: tom-liste
    503: ikke-tilgjengelig
  mock:
    enabled: false

spring:
  security:
    user:
      name: user
      password: password

## Altinn integration
altinn:
  escapeScopenames: false
  #  delegationsEndpoint: http://localhost:9991/altinn-mock/delegations
#  connectTimeout: <%= @connect_timeout %>
#  readTimeout: <%= @read_timeout %>
  keystore:
    type: JKS
    path: classpath:difi-testsertifikat.jks
    password: oBr8YZuZsbic4gpP
    keyAlias: avsender
    keyPassword: oBr8YZuZsbic4gpP
  serviceEndpoint: https://at23.altinn.cloud/maskinporten-api

maskinporten:
  iss: altinn-gateway
#  aud: https://eid-systest-web01.dmz.local/maskinporten/
#  aud: https://maskinporten-test1.difi.eon.no/
#  tokenEndpoint: https://maskinporten-test1.difi.eon.no/token
  aud: https://oidc-test1.difi.eon.no/idporten-oidc-provider/
  resource: https://tt02.altinn.no/maskinporten-api/
  tokenEndpoint: https://oidc-test1.difi.eon.no/idporten-oidc-provider/token
  scope: altinn:maskinporten/delegations.admin



